//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.9.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using ex_8.HelperClasses;
using ex_8.FactoryClasses;
using ex_8.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace ex_8.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END

	/// <summary>Entity class which represents the entity 'Ingredient'.<br/><br/></summary>
	[Serializable]
	public partial class IngredientEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END
	
	{
		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END

		private static IngredientEntityStaticMetaData _staticMetaData = new IngredientEntityStaticMetaData();
		private static IngredientRelations _relationsFactory = new IngredientRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class IngredientEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public IngredientEntityStaticMetaData()
			{
				SetEntityCoreInfo("IngredientEntity", InheritanceHierarchyType.None, false, (int)ex_8.EntityType.IngredientEntity, typeof(IngredientEntity), typeof(IngredientEntityFactory), false);
			}
		}

		/// <summary>Static ctor</summary>
		static IngredientEntity()
		{
		}

		/// <summary> CTor</summary>
		public IngredientEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public IngredientEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this IngredientEntity</param>
		public IngredientEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Ingredient which data should be fetched into this Ingredient object</param>
		public IngredientEntity(System.Guid id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Ingredient which data should be fetched into this Ingredient object</param>
		/// <param name="validator">The custom validator object for this IngredientEntity</param>
		public IngredientEntity(System.Guid id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected IngredientEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this IngredientEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END


			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static IngredientRelations Relations { get { return _relationsFactory; } }

		/// <summary>The Content property of the Entity Ingredient<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Ingredient"."content".<br/>Table field type characteristics (type, precision, scale, length): Text, 0, 0, 1073741824.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Content
		{
			get { return (System.String)GetValue((int)IngredientFieldIndex.Content, true); }
			set	{ SetValue((int)IngredientFieldIndex.Content, value); }
		}

		/// <summary>The Id property of the Entity Ingredient<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Ingredient"."id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Guid Id
		{
			get { return (System.Guid)GetValue((int)IngredientFieldIndex.Id, true); }
			set	{ SetValue((int)IngredientFieldIndex.Id, value); }
		}
		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END


	}
}

namespace ex_8
{
	public enum IngredientFieldIndex
	{
		///<summary>Content. </summary>
		Content,
		///<summary>Id. </summary>
		Id,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace ex_8.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: Ingredient. </summary>
	public partial class IngredientRelations: RelationFactory
	{

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticIngredientRelations
	{

		/// <summary>CTor</summary>
		static StaticIngredientRelations() { }
	}
}
