//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.9.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using ex_8.HelperClasses;
using ex_8.FactoryClasses;
using ex_8.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace ex_8.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END

	/// <summary>Entity class which represents the entity 'Instruction'.<br/><br/></summary>
	[Serializable]
	public partial class InstructionEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END
	
	{
		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END

		private static InstructionEntityStaticMetaData _staticMetaData = new InstructionEntityStaticMetaData();
		private static InstructionRelations _relationsFactory = new InstructionRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class InstructionEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public InstructionEntityStaticMetaData()
			{
				SetEntityCoreInfo("InstructionEntity", InheritanceHierarchyType.None, false, (int)ex_8.EntityType.InstructionEntity, typeof(InstructionEntity), typeof(InstructionEntityFactory), false);
			}
		}

		/// <summary>Static ctor</summary>
		static InstructionEntity()
		{
		}

		/// <summary> CTor</summary>
		public InstructionEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public InstructionEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this InstructionEntity</param>
		public InstructionEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Instruction which data should be fetched into this Instruction object</param>
		public InstructionEntity(System.Guid id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Instruction which data should be fetched into this Instruction object</param>
		/// <param name="validator">The custom validator object for this InstructionEntity</param>
		public InstructionEntity(System.Guid id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected InstructionEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this InstructionEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END


			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static InstructionRelations Relations { get { return _relationsFactory; } }

		/// <summary>The Content property of the Entity Instruction<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Instruction"."content".<br/>Table field type characteristics (type, precision, scale, length): Text, 0, 0, 1073741824.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Content
		{
			get { return (System.String)GetValue((int)InstructionFieldIndex.Content, true); }
			set	{ SetValue((int)InstructionFieldIndex.Content, value); }
		}

		/// <summary>The Id property of the Entity Instruction<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Instruction"."id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Guid Id
		{
			get { return (System.Guid)GetValue((int)InstructionFieldIndex.Id, true); }
			set	{ SetValue((int)InstructionFieldIndex.Id, value); }
		}
		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END


	}
}

namespace ex_8
{
	public enum InstructionFieldIndex
	{
		///<summary>Content. </summary>
		Content,
		///<summary>Id. </summary>
		Id,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace ex_8.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: Instruction. </summary>
	public partial class InstructionRelations: RelationFactory
	{

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticInstructionRelations
	{

		/// <summary>CTor</summary>
		static StaticInstructionRelations() { }
	}
}
