//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.9.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using ex_8.HelperClasses;
using ex_8.FactoryClasses;
using ex_8.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace ex_8.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END

	/// <summary>Entity class which represents the entity 'RecipeIngredient'.<br/><br/></summary>
	[Serializable]
	public partial class RecipeIngredientEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END
	
	{
		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END

		private static RecipeIngredientEntityStaticMetaData _staticMetaData = new RecipeIngredientEntityStaticMetaData();
		private static RecipeIngredientRelations _relationsFactory = new RecipeIngredientRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class RecipeIngredientEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public RecipeIngredientEntityStaticMetaData()
			{
				SetEntityCoreInfo("RecipeIngredientEntity", InheritanceHierarchyType.None, false, (int)ex_8.EntityType.RecipeIngredientEntity, typeof(RecipeIngredientEntity), typeof(RecipeIngredientEntityFactory), false);
			}
		}

		/// <summary>Static ctor</summary>
		static RecipeIngredientEntity()
		{
		}

		/// <summary> CTor</summary>
		public RecipeIngredientEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public RecipeIngredientEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this RecipeIngredientEntity</param>
		public RecipeIngredientEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for RecipeIngredient which data should be fetched into this RecipeIngredient object</param>
		public RecipeIngredientEntity(System.Guid id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for RecipeIngredient which data should be fetched into this RecipeIngredient object</param>
		/// <param name="validator">The custom validator object for this RecipeIngredientEntity</param>
		public RecipeIngredientEntity(System.Guid id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected RecipeIngredientEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this RecipeIngredientEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END


			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static RecipeIngredientRelations Relations { get { return _relationsFactory; } }

		/// <summary>The Category property of the Entity RecipeIngredient<br/><br/></summary>
		/// <remarks>Mapped on  table field: "RecipeIngredient"."category".<br/>Table field type characteristics (type, precision, scale, length): Text, 0, 0, 1073741824.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Category
		{
			get { return (System.String)GetValue((int)RecipeIngredientFieldIndex.Category, true); }
			set	{ SetValue((int)RecipeIngredientFieldIndex.Category, value); }
		}

		/// <summary>The Id property of the Entity RecipeIngredient<br/><br/></summary>
		/// <remarks>Mapped on  table field: "RecipeIngredient"."id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Guid Id
		{
			get { return (System.Guid)GetValue((int)RecipeIngredientFieldIndex.Id, true); }
			set	{ SetValue((int)RecipeIngredientFieldIndex.Id, value); }
		}

		/// <summary>The Rank property of the Entity RecipeIngredient<br/><br/></summary>
		/// <remarks>Mapped on  table field: "RecipeIngredient"."rank".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int32 Rank
		{
			get { return (System.Int32)GetValue((int)RecipeIngredientFieldIndex.Rank, true); }
			set	{ SetValue((int)RecipeIngredientFieldIndex.Rank, value); }
		}

		/// <summary>The Recipe property of the Entity RecipeIngredient<br/><br/></summary>
		/// <remarks>Mapped on  table field: "RecipeIngredient"."recipe".<br/>Table field type characteristics (type, precision, scale, length): Text, 0, 0, 1073741824.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Recipe
		{
			get { return (System.String)GetValue((int)RecipeIngredientFieldIndex.Recipe, true); }
			set	{ SetValue((int)RecipeIngredientFieldIndex.Recipe, value); }
		}
		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END


	}
}

namespace ex_8
{
	public enum RecipeIngredientFieldIndex
	{
		///<summary>Category. </summary>
		Category,
		///<summary>Id. </summary>
		Id,
		///<summary>Rank. </summary>
		Rank,
		///<summary>Recipe. </summary>
		Recipe,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace ex_8.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: RecipeIngredient. </summary>
	public partial class RecipeIngredientRelations: RelationFactory
	{

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticRecipeIngredientRelations
	{

		/// <summary>CTor</summary>
		static StaticRecipeIngredientRelations() { }
	}
}
