//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.9.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using ex_8.HelperClasses;
using ex_8.FactoryClasses;
using ex_8.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace ex_8.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END

	/// <summary>Entity class which represents the entity 'Recipe'.<br/><br/></summary>
	[Serializable]
	public partial class RecipeEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END
	
	{
		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END

		private static RecipeEntityStaticMetaData _staticMetaData = new RecipeEntityStaticMetaData();
		private static RecipeRelations _relationsFactory = new RecipeRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class RecipeEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public RecipeEntityStaticMetaData()
			{
				SetEntityCoreInfo("RecipeEntity", InheritanceHierarchyType.None, false, (int)ex_8.EntityType.RecipeEntity, typeof(RecipeEntity), typeof(RecipeEntityFactory), false);
			}
		}

		/// <summary>Static ctor</summary>
		static RecipeEntity()
		{
		}

		/// <summary> CTor</summary>
		public RecipeEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public RecipeEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this RecipeEntity</param>
		public RecipeEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Recipe which data should be fetched into this Recipe object</param>
		public RecipeEntity(System.Guid id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Recipe which data should be fetched into this Recipe object</param>
		/// <param name="validator">The custom validator object for this RecipeEntity</param>
		public RecipeEntity(System.Guid id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected RecipeEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this RecipeEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END


			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static RecipeRelations Relations { get { return _relationsFactory; } }

		/// <summary>The Id property of the Entity Recipe<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Recipe"."id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Guid Id
		{
			get { return (System.Guid)GetValue((int)RecipeFieldIndex.Id, true); }
			set	{ SetValue((int)RecipeFieldIndex.Id, value); }
		}

		/// <summary>The Title property of the Entity Recipe<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Recipe"."title".<br/>Table field type characteristics (type, precision, scale, length): Text, 0, 0, 1073741824.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Title
		{
			get { return (System.String)GetValue((int)RecipeFieldIndex.Title, true); }
			set	{ SetValue((int)RecipeFieldIndex.Title, value); }
		}
		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END


	}
}

namespace ex_8
{
	public enum RecipeFieldIndex
	{
		///<summary>Id. </summary>
		Id,
		///<summary>Title. </summary>
		Title,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace ex_8.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: Recipe. </summary>
	public partial class RecipeRelations: RelationFactory
	{

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticRecipeRelations
	{

		/// <summary>CTor</summary>
		static StaticRecipeRelations() { }
	}
}
