//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.9.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace ex_8.HelperClasses
{
	/// <summary>Field Creation Class for entity CategoryEntity</summary>
	public partial class CategoryFields
	{
		/// <summary>Creates a new CategoryEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CategoryFieldIndex.Id); }}
		/// <summary>Creates a new CategoryEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CategoryFieldIndex.Name); }}
	}

	/// <summary>Field Creation Class for entity IngredientEntity</summary>
	public partial class IngredientFields
	{
		/// <summary>Creates a new IngredientEntity.Content field instance</summary>
		public static EntityField2 Content { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(IngredientFieldIndex.Content); }}
		/// <summary>Creates a new IngredientEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(IngredientFieldIndex.Id); }}
	}

	/// <summary>Field Creation Class for entity InstructionEntity</summary>
	public partial class InstructionFields
	{
		/// <summary>Creates a new InstructionEntity.Content field instance</summary>
		public static EntityField2 Content { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(InstructionFieldIndex.Content); }}
		/// <summary>Creates a new InstructionEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(InstructionFieldIndex.Id); }}
	}

	/// <summary>Field Creation Class for entity RecipeEntity</summary>
	public partial class RecipeFields
	{
		/// <summary>Creates a new RecipeEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(RecipeFieldIndex.Id); }}
		/// <summary>Creates a new RecipeEntity.Title field instance</summary>
		public static EntityField2 Title { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(RecipeFieldIndex.Title); }}
	}

	/// <summary>Field Creation Class for entity RecipeCategoryEntity</summary>
	public partial class RecipeCategoryFields
	{
		/// <summary>Creates a new RecipeCategoryEntity.Category field instance</summary>
		public static EntityField2 Category { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(RecipeCategoryFieldIndex.Category); }}
		/// <summary>Creates a new RecipeCategoryEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(RecipeCategoryFieldIndex.Id); }}
		/// <summary>Creates a new RecipeCategoryEntity.Recipe field instance</summary>
		public static EntityField2 Recipe { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(RecipeCategoryFieldIndex.Recipe); }}
	}

	/// <summary>Field Creation Class for entity RecipeIngredientEntity</summary>
	public partial class RecipeIngredientFields
	{
		/// <summary>Creates a new RecipeIngredientEntity.Category field instance</summary>
		public static EntityField2 Category { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(RecipeIngredientFieldIndex.Category); }}
		/// <summary>Creates a new RecipeIngredientEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(RecipeIngredientFieldIndex.Id); }}
		/// <summary>Creates a new RecipeIngredientEntity.Rank field instance</summary>
		public static EntityField2 Rank { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(RecipeIngredientFieldIndex.Rank); }}
		/// <summary>Creates a new RecipeIngredientEntity.Recipe field instance</summary>
		public static EntityField2 Recipe { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(RecipeIngredientFieldIndex.Recipe); }}
	}

	/// <summary>Field Creation Class for entity RecipeInstructionEntity</summary>
	public partial class RecipeInstructionFields
	{
		/// <summary>Creates a new RecipeInstructionEntity.Category field instance</summary>
		public static EntityField2 Category { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(RecipeInstructionFieldIndex.Category); }}
		/// <summary>Creates a new RecipeInstructionEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(RecipeInstructionFieldIndex.Id); }}
		/// <summary>Creates a new RecipeInstructionEntity.Rank field instance</summary>
		public static EntityField2 Rank { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(RecipeInstructionFieldIndex.Rank); }}
		/// <summary>Creates a new RecipeInstructionEntity.Recipe field instance</summary>
		public static EntityField2 Recipe { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(RecipeInstructionFieldIndex.Recipe); }}
	}

	/// <summary>Field Creation Class for entity UserEntity</summary>
	public partial class UserFields
	{
		/// <summary>Creates a new UserEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.Id); }}
		/// <summary>Creates a new UserEntity.PasswordHash field instance</summary>
		public static EntityField2 PasswordHash { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.PasswordHash); }}
		/// <summary>Creates a new UserEntity.PasswordSalt field instance</summary>
		public static EntityField2 PasswordSalt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.PasswordSalt); }}
		/// <summary>Creates a new UserEntity.TokenCreatedAt field instance</summary>
		public static EntityField2 TokenCreatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.TokenCreatedAt); }}
		/// <summary>Creates a new UserEntity.TokenExpiresAt field instance</summary>
		public static EntityField2 TokenExpiresAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.TokenExpiresAt); }}
		/// <summary>Creates a new UserEntity.UserName field instance</summary>
		public static EntityField2 UserName { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.UserName); }}
	}
	

}