//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.9.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using ex_8.FactoryClasses;
using ex_8.RelationClasses;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace ex_8.HelperClasses
{
	/// <summary>Singleton implementation of the ModelInfoProvider. This class is the singleton wrapper through which the actual instance is retrieved.</summary>
	public static class ModelInfoProviderSingleton
	{
		private static readonly IModelInfoProvider _providerInstance = new ModelInfoProviderCore();

		/// <summary>Dummy static constructor to make sure threadsafe initialization is performed.</summary>
		static ModelInfoProviderSingleton()	{ }

		/// <summary>Gets the singleton instance of the ModelInfoProviderCore</summary>
		/// <returns>Instance of the FieldInfoProvider.</returns>
		public static IModelInfoProvider GetInstance()
		{
			return _providerInstance;
		}
	}

	/// <summary>Actual implementation of the ModelInfoProvider.</summary>
	internal class ModelInfoProviderCore : ModelInfoProviderBase
	{
		/// <summary>Initializes a new instance of the <see cref="ModelInfoProviderCore"/> class.</summary>
		internal ModelInfoProviderCore()
		{
			Init();
		}

		/// <summary>Method which initializes the internal datastores.</summary>
		private void Init()
		{
			this.InitClass();
			InitCategoryEntityInfo();
			InitIngredientEntityInfo();
			InitInstructionEntityInfo();
			InitRecipeEntityInfo();
			InitRecipeCategoryEntityInfo();
			InitRecipeIngredientEntityInfo();
			InitRecipeInstructionEntityInfo();
			InitUserEntityInfo();
			this.BuildInternalStructures();
		}

		/// <summary>Inits CategoryEntity's info objects</summary>
		private void InitCategoryEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CategoryFieldIndex), "CategoryEntity");
			this.AddElementFieldInfo("CategoryEntity", "Id", typeof(System.Guid), true, false, false, false,  (int)CategoryFieldIndex.Id, 0, 0, 0);
			this.AddElementFieldInfo("CategoryEntity", "Name", typeof(System.String), false, false, false, false,  (int)CategoryFieldIndex.Name, 1073741824, 0, 0);
		}

		/// <summary>Inits IngredientEntity's info objects</summary>
		private void InitIngredientEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(IngredientFieldIndex), "IngredientEntity");
			this.AddElementFieldInfo("IngredientEntity", "Content", typeof(System.String), false, false, false, false,  (int)IngredientFieldIndex.Content, 1073741824, 0, 0);
			this.AddElementFieldInfo("IngredientEntity", "Id", typeof(System.Guid), true, false, false, false,  (int)IngredientFieldIndex.Id, 0, 0, 0);
		}

		/// <summary>Inits InstructionEntity's info objects</summary>
		private void InitInstructionEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(InstructionFieldIndex), "InstructionEntity");
			this.AddElementFieldInfo("InstructionEntity", "Content", typeof(System.String), false, false, false, false,  (int)InstructionFieldIndex.Content, 1073741824, 0, 0);
			this.AddElementFieldInfo("InstructionEntity", "Id", typeof(System.Guid), true, false, false, false,  (int)InstructionFieldIndex.Id, 0, 0, 0);
		}

		/// <summary>Inits RecipeEntity's info objects</summary>
		private void InitRecipeEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(RecipeFieldIndex), "RecipeEntity");
			this.AddElementFieldInfo("RecipeEntity", "Id", typeof(System.Guid), true, false, false, false,  (int)RecipeFieldIndex.Id, 0, 0, 0);
			this.AddElementFieldInfo("RecipeEntity", "Title", typeof(System.String), false, false, false, false,  (int)RecipeFieldIndex.Title, 1073741824, 0, 0);
		}

		/// <summary>Inits RecipeCategoryEntity's info objects</summary>
		private void InitRecipeCategoryEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(RecipeCategoryFieldIndex), "RecipeCategoryEntity");
			this.AddElementFieldInfo("RecipeCategoryEntity", "Category", typeof(System.String), false, false, false, false,  (int)RecipeCategoryFieldIndex.Category, 1073741824, 0, 0);
			this.AddElementFieldInfo("RecipeCategoryEntity", "Id", typeof(System.Guid), true, false, false, false,  (int)RecipeCategoryFieldIndex.Id, 0, 0, 0);
			this.AddElementFieldInfo("RecipeCategoryEntity", "Recipe", typeof(System.String), false, false, false, false,  (int)RecipeCategoryFieldIndex.Recipe, 1073741824, 0, 0);
		}

		/// <summary>Inits RecipeIngredientEntity's info objects</summary>
		private void InitRecipeIngredientEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(RecipeIngredientFieldIndex), "RecipeIngredientEntity");
			this.AddElementFieldInfo("RecipeIngredientEntity", "Category", typeof(System.Guid), false, false, false, false,  (int)RecipeIngredientFieldIndex.Category, 0, 0, 0);
			this.AddElementFieldInfo("RecipeIngredientEntity", "Id", typeof(System.Guid), true, false, false, false,  (int)RecipeIngredientFieldIndex.Id, 0, 0, 0);
			this.AddElementFieldInfo("RecipeIngredientEntity", "Rank", typeof(System.Int32), false, false, false, false,  (int)RecipeIngredientFieldIndex.Rank, 0, 0, 10);
			this.AddElementFieldInfo("RecipeIngredientEntity", "Recipe", typeof(System.Guid), false, false, false, false,  (int)RecipeIngredientFieldIndex.Recipe, 0, 0, 0);
		}

		/// <summary>Inits RecipeInstructionEntity's info objects</summary>
		private void InitRecipeInstructionEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(RecipeInstructionFieldIndex), "RecipeInstructionEntity");
			this.AddElementFieldInfo("RecipeInstructionEntity", "Category", typeof(System.String), false, false, false, false,  (int)RecipeInstructionFieldIndex.Category, 1073741824, 0, 0);
			this.AddElementFieldInfo("RecipeInstructionEntity", "Id", typeof(System.Guid), true, false, false, false,  (int)RecipeInstructionFieldIndex.Id, 0, 0, 0);
			this.AddElementFieldInfo("RecipeInstructionEntity", "Rank", typeof(System.Int32), false, false, false, false,  (int)RecipeInstructionFieldIndex.Rank, 0, 0, 10);
			this.AddElementFieldInfo("RecipeInstructionEntity", "Recipe", typeof(System.String), false, false, false, false,  (int)RecipeInstructionFieldIndex.Recipe, 1073741824, 0, 0);
		}

		/// <summary>Inits UserEntity's info objects</summary>
		private void InitUserEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(UserFieldIndex), "UserEntity");
			this.AddElementFieldInfo("UserEntity", "Id", typeof(System.Guid), true, false, false, false,  (int)UserFieldIndex.Id, 0, 0, 0);
			this.AddElementFieldInfo("UserEntity", "PasswordHash", typeof(System.String), false, false, false, false,  (int)UserFieldIndex.PasswordHash, 1073741824, 0, 0);
			this.AddElementFieldInfo("UserEntity", "PasswordSalt", typeof(System.String), false, false, false, false,  (int)UserFieldIndex.PasswordSalt, 1073741824, 0, 0);
			this.AddElementFieldInfo("UserEntity", "TokenCreatedAt", typeof(System.DateTime), false, false, false, false,  (int)UserFieldIndex.TokenCreatedAt, 0, 0, 0);
			this.AddElementFieldInfo("UserEntity", "TokenExpiresAt", typeof(System.DateTime), false, false, false, false,  (int)UserFieldIndex.TokenExpiresAt, 0, 0, 0);
			this.AddElementFieldInfo("UserEntity", "UserName", typeof(System.String), false, false, false, false,  (int)UserFieldIndex.UserName, 1073741824, 0, 0);
		}
	}
}