//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.9.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace ex_8.DatabaseSpecific
{
	/// <summary>Singleton implementation of the PersistenceInfoProvider. This class is the singleton wrapper through which the actual instance is retrieved.</summary>
	internal static class PersistenceInfoProviderSingleton
	{
		private static readonly IPersistenceInfoProvider _providerInstance = new PersistenceInfoProviderCore();

		/// <summary>Dummy static constructor to make sure threadsafe initialization is performed.</summary>
		static PersistenceInfoProviderSingleton() {	}

		/// <summary>Gets the singleton instance of the PersistenceInfoProviderCore</summary>
		/// <returns>Instance of the PersistenceInfoProvider.</returns>
		public static IPersistenceInfoProvider GetInstance() { return _providerInstance; }
	}

	/// <summary>Actual implementation of the PersistenceInfoProvider. Used by singleton wrapper.</summary>
	internal class PersistenceInfoProviderCore : PersistenceInfoProviderBase
	{
		/// <summary>Initializes a new instance of the <see cref="PersistenceInfoProviderCore"/> class.</summary>
		internal PersistenceInfoProviderCore()
		{
			Init();
		}

		/// <summary>Method which initializes the internal datastores with the structure of hierarchical types.</summary>
		private void Init()
		{
			this.InitClass();
			InitCategoryEntityMappings();
			InitIngredientEntityMappings();
			InitInstructionEntityMappings();
			InitRecipeEntityMappings();
			InitRecipeCategoryEntityMappings();
			InitRecipeIngredientEntityMappings();
			InitRecipeInstructionEntityMappings();
			InitUserEntityMappings();
		}

		/// <summary>Inits CategoryEntity's mappings</summary>
		private void InitCategoryEntityMappings()
		{
			this.AddElementMapping("CategoryEntity", @"mina", @"public", "Category", 2, 0);
			this.AddElementFieldMapping("CategoryEntity", "Id", "id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 0);
			this.AddElementFieldMapping("CategoryEntity", "Name", "name", false, "Text", 1073741824, 0, 0, false, "", null, typeof(System.String), 1);
		}

		/// <summary>Inits IngredientEntity's mappings</summary>
		private void InitIngredientEntityMappings()
		{
			this.AddElementMapping("IngredientEntity", @"mina", @"public", "Ingredient", 2, 0);
			this.AddElementFieldMapping("IngredientEntity", "Content", "content", false, "Text", 1073741824, 0, 0, false, "", null, typeof(System.String), 0);
			this.AddElementFieldMapping("IngredientEntity", "Id", "id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 1);
		}

		/// <summary>Inits InstructionEntity's mappings</summary>
		private void InitInstructionEntityMappings()
		{
			this.AddElementMapping("InstructionEntity", @"mina", @"public", "Instruction", 2, 0);
			this.AddElementFieldMapping("InstructionEntity", "Content", "content", false, "Text", 1073741824, 0, 0, false, "", null, typeof(System.String), 0);
			this.AddElementFieldMapping("InstructionEntity", "Id", "id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 1);
		}

		/// <summary>Inits RecipeEntity's mappings</summary>
		private void InitRecipeEntityMappings()
		{
			this.AddElementMapping("RecipeEntity", @"mina", @"public", "Recipe", 2, 0);
			this.AddElementFieldMapping("RecipeEntity", "Id", "id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 0);
			this.AddElementFieldMapping("RecipeEntity", "Title", "title", false, "Text", 1073741824, 0, 0, false, "", null, typeof(System.String), 1);
		}

		/// <summary>Inits RecipeCategoryEntity's mappings</summary>
		private void InitRecipeCategoryEntityMappings()
		{
			this.AddElementMapping("RecipeCategoryEntity", @"mina", @"public", "RecipeCategory", 3, 0);
			this.AddElementFieldMapping("RecipeCategoryEntity", "Category", "category", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 0);
			this.AddElementFieldMapping("RecipeCategoryEntity", "Id", "id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 1);
			this.AddElementFieldMapping("RecipeCategoryEntity", "Recipe", "recipe", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 2);
		}

		/// <summary>Inits RecipeIngredientEntity's mappings</summary>
		private void InitRecipeIngredientEntityMappings()
		{
			this.AddElementMapping("RecipeIngredientEntity", @"mina", @"public", "RecipeIngredient", 4, 0);
			this.AddElementFieldMapping("RecipeIngredientEntity", "Id", "id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 0);
			this.AddElementFieldMapping("RecipeIngredientEntity", "Ingredient", "ingredient", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 1);
			this.AddElementFieldMapping("RecipeIngredientEntity", "Rank", "rank", false, "Integer", 0, 10, 0, false, "", null, typeof(System.Int32), 2);
			this.AddElementFieldMapping("RecipeIngredientEntity", "Recipe", "recipe", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 3);
		}

		/// <summary>Inits RecipeInstructionEntity's mappings</summary>
		private void InitRecipeInstructionEntityMappings()
		{
			this.AddElementMapping("RecipeInstructionEntity", @"mina", @"public", "RecipeInstruction", 4, 0);
			this.AddElementFieldMapping("RecipeInstructionEntity", "Id", "id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 0);
			this.AddElementFieldMapping("RecipeInstructionEntity", "Instruction", "instruction", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 1);
			this.AddElementFieldMapping("RecipeInstructionEntity", "Rank", "rank", false, "Integer", 0, 10, 0, false, "", null, typeof(System.Int32), 2);
			this.AddElementFieldMapping("RecipeInstructionEntity", "Recipe", "recipe", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 3);
		}

		/// <summary>Inits UserEntity's mappings</summary>
		private void InitUserEntityMappings()
		{
			this.AddElementMapping("UserEntity", @"mina", @"public", "User", 6, 0);
			this.AddElementFieldMapping("UserEntity", "Id", "id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 0);
			this.AddElementFieldMapping("UserEntity", "PasswordHash", "passwordHash", false, "Text", 1073741824, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("UserEntity", "PasswordSalt", "passwordSalt", false, "Text", 1073741824, 0, 0, false, "", null, typeof(System.String), 2);
			this.AddElementFieldMapping("UserEntity", "TokenCreatedAt", "tokenCreatedAt", false, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 3);
			this.AddElementFieldMapping("UserEntity", "TokenExpiresAt", "tokenExpiresAt", false, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 4);
			this.AddElementFieldMapping("UserEntity", "UserName", "userName", false, "Text", 1073741824, 0, 0, false, "", null, typeof(System.String), 5);
		}

	}
}
